-- Cache publica de la cola real de AzuraCast (hasta 10 items, con genero y
-- duracion). El endpoint de cola de AzuraCast exige API key, asi que no se
-- puede leer directo desde el cliente sin exponerla — un cron sincroniza
-- esta tabla cada 3 minutos via la Edge Function sync-radio-queue, y el
-- cliente solo hace un SELECT publico normal, igual que radio_health_checks.

CREATE TABLE IF NOT EXISTS public.radio_queue_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (octet_length(queue::TEXT) <= 20000),
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS radio_queue_cache_synced_at_idx
  ON public.radio_queue_cache (synced_at DESC);

ALTER TABLE public.radio_queue_cache ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS radio_queue_cache_public_read ON public.radio_queue_cache;
CREATE POLICY radio_queue_cache_public_read ON public.radio_queue_cache
  FOR SELECT USING (true);

REVOKE ALL ON public.radio_queue_cache FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.radio_queue_cache TO anon, authenticated;
GRANT ALL ON public.radio_queue_cache TO service_role;

CREATE OR REPLACE FUNCTION public.trigger_radio_queue_sync()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_secret TEXT;
  v_ref TEXT;
BEGIN
  SELECT decrypted_secret INTO v_secret FROM vault.decrypted_secrets WHERE name = 'cron_alert_secret';
  SELECT decrypted_secret INTO v_ref FROM vault.decrypted_secrets WHERE name = 'supabase_project_ref';
  IF v_secret IS NULL OR v_ref IS NULL THEN RETURN; END IF;

  PERFORM net.http_post(
    url := 'https://' || v_ref || '.supabase.co/functions/v1/sync-radio-queue',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
    body := '{}'::JSONB
  );
END;
$$;

REVOKE ALL ON FUNCTION public.trigger_radio_queue_sync() FROM PUBLIC, anon, authenticated;

DO $$
DECLARE v_job BIGINT;
BEGIN
  FOR v_job IN SELECT jobid FROM cron.job WHERE jobname = 'polyfauna-radio-queue-sync' LOOP
    PERFORM cron.unschedule(v_job);
  END LOOP;
END $$;

SELECT cron.schedule('polyfauna-radio-queue-sync', '*/3 * * * *', $$SELECT public.trigger_radio_queue_sync();$$);
