-- Resiliencia de radio: eventos cliente, monitor externo y alertas operativas.

ALTER TABLE public.usage_events
  DROP CONSTRAINT IF EXISTS usage_events_event_name_check;

ALTER TABLE public.usage_events
  ADD CONSTRAINT usage_events_event_name_check CHECK (
    event_name IN (
      'session_heartbeat', 'route_view', 'stream_start', 'stream_connecting',
      'stream_playing', 'stream_stalled', 'stream_reconnect_attempt',
      'stream_recovered', 'stream_failed', 'media_start', 'event_view',
      'checkout_start', 'checkout_ready', 'ticket_claimed', 'checkout_error'
    )
  );

CREATE TABLE IF NOT EXISTS public.radio_health_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  healthy BOOLEAN NOT NULL,
  api_ok BOOLEAN NOT NULL,
  is_online BOOLEAN NOT NULL,
  mounts JSONB NOT NULL DEFAULT '[]'::JSONB CHECK (octet_length(mounts::TEXT) <= 12000),
  latency_ms INTEGER NOT NULL CHECK (latency_ms >= 0),
  error_code TEXT CHECK (char_length(error_code) <= 80),
  checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS radio_health_checks_checked_at_idx
  ON public.radio_health_checks (checked_at DESC);

ALTER TABLE public.radio_health_checks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS radio_health_checks_admin_read ON public.radio_health_checks;
CREATE POLICY radio_health_checks_admin_read ON public.radio_health_checks
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles
    WHERE profiles.id = (SELECT auth.uid()) AND profiles.role = 'admin'
  ));

REVOKE ALL ON public.radio_health_checks FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.radio_health_checks TO authenticated;
GRANT ALL ON public.radio_health_checks TO service_role;

CREATE OR REPLACE FUNCTION public.get_radio_health_alerts_unsafe()
RETURNS TABLE (
  severity TEXT, code TEXT, title TEXT, detail TEXT, action TEXT,
  affected_count BIGINT, latest_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_latest public.radio_health_checks%ROWTYPE;
  v_recent_failures BIGINT;
BEGIN
  SELECT * INTO v_latest
  FROM public.radio_health_checks
  ORDER BY checked_at DESC
  LIMIT 1;

  IF v_latest.id IS NULL OR v_latest.checked_at < NOW() - INTERVAL '15 minutes' THEN
    RETURN QUERY SELECT
      'warning'::TEXT, 'radio_monitor_stale'::TEXT,
      'Monitor de radio sin datos recientes'::TEXT,
      'No se ha recibido una comprobacion completa de la radio en los ultimos 15 minutos.'::TEXT,
      'Revisar pg_cron, pg_net y la Edge Function check-radio-health.'::TEXT,
      1::BIGINT, v_latest.checked_at;
    RETURN;
  END IF;

  IF NOT v_latest.healthy THEN
    SELECT COUNT(*) INTO v_recent_failures
    FROM (
      SELECT healthy FROM public.radio_health_checks ORDER BY checked_at DESC LIMIT 2
    ) recent
    WHERE NOT healthy;

    RETURN QUERY SELECT
      CASE WHEN v_recent_failures >= 2 THEN 'critical' ELSE 'warning' END::TEXT,
      'radio_stream_unhealthy'::TEXT,
      'Radio con fallos de disponibilidad'::TEXT,
      ('La ultima comprobacion fallo: ' || COALESCE(v_latest.error_code, 'error_desconocido') || '.')::TEXT,
      'Revisar el estado de Liquidsoap, Icecast y los mounts 192/128/64 kbps.'::TEXT,
      v_recent_failures, v_latest.checked_at;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.get_radio_health_alerts_unsafe() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_radio_health_alerts()
RETURNS TABLE (
  severity TEXT, code TEXT, title TEXT, detail TEXT, action TEXT,
  affected_count BIGINT, latest_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  ) THEN
    RAISE EXCEPTION 'Access denied';
  END IF;
  RETURN QUERY SELECT * FROM public.get_radio_health_alerts_unsafe();
END;
$$;

REVOKE ALL ON FUNCTION public.get_radio_health_alerts() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_radio_health_alerts() TO authenticated;

CREATE OR REPLACE FUNCTION public.trigger_radio_health_check()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_secret TEXT;
  v_ref TEXT;
BEGIN
  SELECT decrypted_secret INTO v_secret FROM vault.decrypted_secrets WHERE name = 'cron_alert_secret';
  SELECT decrypted_secret INTO v_ref FROM vault.decrypted_secrets WHERE name = 'supabase_project_ref';
  IF v_secret IS NULL OR v_ref IS NULL THEN RETURN; END IF;

  PERFORM net.http_post(
    url := 'https://' || v_ref || '.supabase.co/functions/v1/check-radio-health',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
    body := '{}'::JSONB
  );
END;
$$;

REVOKE ALL ON FUNCTION public.trigger_radio_health_check() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.trigger_radio_alert_email()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_secret TEXT;
  v_ref TEXT;
  v_payload JSONB;
BEGIN
  SELECT decrypted_secret INTO v_secret FROM vault.decrypted_secrets WHERE name = 'cron_alert_secret';
  SELECT decrypted_secret INTO v_ref FROM vault.decrypted_secrets WHERE name = 'supabase_project_ref';
  IF v_secret IS NULL OR v_ref IS NULL THEN RETURN; END IF;

  SELECT jsonb_agg(jsonb_build_object(
    'severity', a.severity, 'code', a.code, 'title', a.title,
    'detail', a.detail, 'action', a.action,
    'affected_count', a.affected_count, 'latest_at', a.latest_at
  )) INTO v_payload
  FROM public.get_radio_health_alerts_unsafe() a
  WHERE a.severity = 'critical'
    AND NOT EXISTS (
      SELECT 1 FROM public.operational_alert_notifications n
      WHERE n.code = a.code AND n.notified_at > NOW() - INTERVAL '2 hours'
    );

  IF v_payload IS NULL THEN RETURN; END IF;

  PERFORM net.http_post(
    url := 'https://' || v_ref || '.supabase.co/functions/v1/send-operational-alert',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
    body := jsonb_build_object('alerts', v_payload)
  );

  INSERT INTO public.operational_alert_notifications (code, notified_at)
  SELECT (a->>'code'), NOW() FROM jsonb_array_elements(v_payload) a
  ON CONFLICT (code) DO UPDATE SET notified_at = NOW();
END;
$$;

REVOKE ALL ON FUNCTION public.trigger_radio_alert_email() FROM PUBLIC, anon, authenticated;

DO $$
DECLARE v_job BIGINT;
BEGIN
  FOR v_job IN SELECT jobid FROM cron.job WHERE jobname IN ('polyfauna-radio-health', 'polyfauna-radio-alert-email') LOOP
    PERFORM cron.unschedule(v_job);
  END LOOP;
END $$;

SELECT cron.schedule('polyfauna-radio-health', '*/5 * * * *', $$SELECT public.trigger_radio_health_check();$$);
SELECT cron.schedule('polyfauna-radio-alert-email', '*/15 * * * *', $$SELECT public.trigger_radio_alert_email();$$);
